name: trainer
inputs:
  - {name: processed_train_data_path, type: Dataset}
outputs:
  - {name: model_path, type: Model}
implementation:
  container:
    image: ${image}
    args: 
      - {inputPath: processed_train_data_path}
      - {outputPath: model_path}
      